server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-a7shddcm.sql.tencentcdb.com:23974/springboot_demo
    username: root
    password: 890qweASD
  #    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
  #    username: ${MYSQL_USERNAME}
  #    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /
    static-path-pattern: /static/images/**

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



