server:
  port: 8080

#    url: jdbc:mysql://sh-cynosdbmysql-grp-a7shddcm.sql.tencentcdb.com:23974/springboot_demo
#    username: root
#    password: 890qweASD
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.29.110.164:3306:springboot_demon
    username: root
    password: 890qweASD
  mvc:
    view:
      suffix: .html
      prefix: /
    static-path-pattern: /static/images/**

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



